// Code generated by "protoc-gen-entpb". DO NOT EDIT

package bare

import (
	context "context"
	uuid "github.com/google/uuid"
	ent "github.com/lesomnus/entpb/internal/example/ent"
	account "github.com/lesomnus/entpb/internal/example/ent/account"
	membership "github.com/lesomnus/entpb/internal/example/ent/membership"
	predicate "github.com/lesomnus/entpb/internal/example/ent/predicate"
	team "github.com/lesomnus/entpb/internal/example/ent/team"
	pb "github.com/lesomnus/entpb/internal/example/pb"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

type MembershipServiceServer struct {
	db *ent.Client
	pb.UnimplementedMembershipServiceServer
}

func NewMembershipServiceServer(db *ent.Client) *MembershipServiceServer {
	return &MembershipServiceServer{db: db}
}
func (s *MembershipServiceServer) Create(ctx context.Context, req *pb.CreateMembershipRequest) (*pb.Membership, error) {
	q := s.db.Membership.Create()
	q.SetRole(toEntRole(req.GetRole()))
	if id, err := GetAccountId(ctx, s.db, req.GetAccount()); err != nil {
		return nil, err
	} else {
		q.SetAccountID(id)
	}
	if id, err := GetTeamId(ctx, s.db, req.GetTeam()); err != nil {
		return nil, err
	} else {
		q.SetTeamID(id)
	}

	res, err := q.Save(ctx)
	if err != nil {
		return nil, ToStatus(err)
	}

	return ToProtoMembership(res), nil
}
func (s *MembershipServiceServer) Delete(ctx context.Context, req *pb.GetMembershipRequest) (*emptypb.Empty, error) {
	p, err := GetMembershipSpecifier(req)
	if err != nil {
		return nil, err
	}
	if _, err := s.db.Membership.Delete().Where(p).Exec(ctx); err != nil {
		return nil, ToStatus(err)
	}

	return &emptypb.Empty{}, nil
}
func (s *MembershipServiceServer) Get(ctx context.Context, req *pb.GetMembershipRequest) (*pb.Membership, error) {
	q := s.db.Membership.Query()
	if p, err := GetMembershipSpecifier(req); err != nil {
		return nil, err
	} else {
		q.Where(p)
	}

	res, err := QueryMembershipWithEdgeIds(q).Only(ctx)
	if err != nil {
		return nil, ToStatus(err)
	}

	return ToProtoMembership(res), nil
}
func QueryMembershipWithEdgeIds(q *ent.MembershipQuery) *ent.MembershipQuery {
	q.WithAccount(func(q *ent.AccountQuery) { q.Select(account.FieldID) })
	q.WithTeam(func(q *ent.TeamQuery) { q.Select(team.FieldID) })

	return q
}
func (s *MembershipServiceServer) Update(ctx context.Context, req *pb.UpdateMembershipRequest) (*pb.Membership, error) {
	id, err := GetMembershipId(ctx, s.db, req.GetKey())
	if err != nil {
		return nil, err
	}

	q := s.db.Membership.UpdateOneID(id)
	if v := req.Role; v != nil {
		q.SetRole(toEntRole(*v))
	}

	res, err := q.Save(ctx)
	if err != nil {
		return nil, ToStatus(err)
	}

	return ToProtoMembership(res), nil
}
func ToProtoMembership(v *ent.Membership) *pb.Membership {
	m := &pb.Membership{}
	m.Id = v.ID[:]
	m.DateCreated = timestamppb.New(v.DateCreated)
	m.Role = toPbRole(v.Role)
	if v := v.Edges.Account; v != nil {
		m.Account = ToProtoAccount(v)
	}
	if v := v.Edges.Team; v != nil {
		m.Team = ToProtoTeam(v)
	}
	return m
}
func GetMembershipId(ctx context.Context, db *ent.Client, req *pb.GetMembershipRequest) (uuid.UUID, error) {
	var r uuid.UUID
	if v, err := uuid.FromBytes(req.GetId()); err != nil {
		return r, status.Errorf(codes.InvalidArgument, "id: %s", err)
	} else {
		return v, nil
	}
}
func GetMembershipSpecifier(req *pb.GetMembershipRequest) (predicate.Membership, error) {
	if v, err := uuid.FromBytes(req.GetId()); err != nil {
		return nil, status.Errorf(codes.InvalidArgument, "id: %s", err)
	} else {
		return membership.IDEQ(v), nil
	}
}
