// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Identity is the predicate function for identity builders.
type Identity func(*sql.Selector)

// Invitation is the predicate function for invitation builders.
type Invitation func(*sql.Selector)

// Membership is the predicate function for membership builders.
type Membership func(*sql.Selector)

// Silo is the predicate function for silo builders.
type Silo func(*sql.Selector)

// Team is the predicate function for team builders.
type Team func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
