// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/lesomnus/entpb/internal/example/ent/account"
	"github.com/lesomnus/entpb/internal/example/ent/invitation"
	"github.com/lesomnus/entpb/internal/example/ent/membership"
	"github.com/lesomnus/entpb/internal/example/ent/predicate"
	"github.com/lesomnus/entpb/internal/example/role"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (au *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetAlias sets the "alias" field.
func (au *AccountUpdate) SetAlias(s string) *AccountUpdate {
	au.mutation.SetAlias(s)
	return au
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (au *AccountUpdate) SetNillableAlias(s *string) *AccountUpdate {
	if s != nil {
		au.SetAlias(*s)
	}
	return au
}

// SetName sets the "name" field.
func (au *AccountUpdate) SetName(s string) *AccountUpdate {
	au.mutation.SetName(s)
	return au
}

// SetNillableName sets the "name" field if the given value is not nil.
func (au *AccountUpdate) SetNillableName(s *string) *AccountUpdate {
	if s != nil {
		au.SetName(*s)
	}
	return au
}

// SetDescription sets the "description" field.
func (au *AccountUpdate) SetDescription(s string) *AccountUpdate {
	au.mutation.SetDescription(s)
	return au
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (au *AccountUpdate) SetNillableDescription(s *string) *AccountUpdate {
	if s != nil {
		au.SetDescription(*s)
	}
	return au
}

// SetRole sets the "role" field.
func (au *AccountUpdate) SetRole(r role.Role) *AccountUpdate {
	au.mutation.SetRole(r)
	return au
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (au *AccountUpdate) SetNillableRole(r *role.Role) *AccountUpdate {
	if r != nil {
		au.SetRole(*r)
	}
	return au
}

// AddMembershipIDs adds the "memberships" edge to the Membership entity by IDs.
func (au *AccountUpdate) AddMembershipIDs(ids ...uuid.UUID) *AccountUpdate {
	au.mutation.AddMembershipIDs(ids...)
	return au
}

// AddMemberships adds the "memberships" edges to the Membership entity.
func (au *AccountUpdate) AddMemberships(m ...*Membership) *AccountUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return au.AddMembershipIDs(ids...)
}

// AddInvitationIDs adds the "invitations" edge to the Invitation entity by IDs.
func (au *AccountUpdate) AddInvitationIDs(ids ...uuid.UUID) *AccountUpdate {
	au.mutation.AddInvitationIDs(ids...)
	return au
}

// AddInvitations adds the "invitations" edges to the Invitation entity.
func (au *AccountUpdate) AddInvitations(i ...*Invitation) *AccountUpdate {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return au.AddInvitationIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (au *AccountUpdate) Mutation() *AccountMutation {
	return au.mutation
}

// ClearMemberships clears all "memberships" edges to the Membership entity.
func (au *AccountUpdate) ClearMemberships() *AccountUpdate {
	au.mutation.ClearMemberships()
	return au
}

// RemoveMembershipIDs removes the "memberships" edge to Membership entities by IDs.
func (au *AccountUpdate) RemoveMembershipIDs(ids ...uuid.UUID) *AccountUpdate {
	au.mutation.RemoveMembershipIDs(ids...)
	return au
}

// RemoveMemberships removes "memberships" edges to Membership entities.
func (au *AccountUpdate) RemoveMemberships(m ...*Membership) *AccountUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return au.RemoveMembershipIDs(ids...)
}

// ClearInvitations clears all "invitations" edges to the Invitation entity.
func (au *AccountUpdate) ClearInvitations() *AccountUpdate {
	au.mutation.ClearInvitations()
	return au
}

// RemoveInvitationIDs removes the "invitations" edge to Invitation entities by IDs.
func (au *AccountUpdate) RemoveInvitationIDs(ids ...uuid.UUID) *AccountUpdate {
	au.mutation.RemoveInvitationIDs(ids...)
	return au
}

// RemoveInvitations removes "invitations" edges to Invitation entities.
func (au *AccountUpdate) RemoveInvitations(i ...*Invitation) *AccountUpdate {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return au.RemoveInvitationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AccountUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AccountUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AccountUpdate) check() error {
	if v, ok := au.mutation.Alias(); ok {
		if err := account.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`ent: validator failed for field "Account.alias": %w`, err)}
		}
	}
	if v, ok := au.mutation.Name(); ok {
		if err := account.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Account.name": %w`, err)}
		}
	}
	if v, ok := au.mutation.Description(); ok {
		if err := account.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Account.description": %w`, err)}
		}
	}
	if v, ok := au.mutation.Role(); ok {
		if err := account.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Account.role": %w`, err)}
		}
	}
	if _, ok := au.mutation.OwnerID(); au.mutation.OwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Account.owner"`)
	}
	if _, ok := au.mutation.SiloID(); au.mutation.SiloCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Account.silo"`)
	}
	return nil
}

func (au *AccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Alias(); ok {
		_spec.SetField(account.FieldAlias, field.TypeString, value)
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := au.mutation.Description(); ok {
		_spec.SetField(account.FieldDescription, field.TypeString, value)
	}
	if value, ok := au.mutation.Role(); ok {
		_spec.SetField(account.FieldRole, field.TypeEnum, value)
	}
	if au.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MembershipsTable,
			Columns: []string{account.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !au.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MembershipsTable,
			Columns: []string{account.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MembershipsTable,
			Columns: []string{account.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.InvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.InvitationsTable,
			Columns: []string{account.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedInvitationsIDs(); len(nodes) > 0 && !au.mutation.InvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.InvitationsTable,
			Columns: []string{account.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.InvitationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.InvitationsTable,
			Columns: []string{account.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetAlias sets the "alias" field.
func (auo *AccountUpdateOne) SetAlias(s string) *AccountUpdateOne {
	auo.mutation.SetAlias(s)
	return auo
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableAlias(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetAlias(*s)
	}
	return auo
}

// SetName sets the "name" field.
func (auo *AccountUpdateOne) SetName(s string) *AccountUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableName(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetName(*s)
	}
	return auo
}

// SetDescription sets the "description" field.
func (auo *AccountUpdateOne) SetDescription(s string) *AccountUpdateOne {
	auo.mutation.SetDescription(s)
	return auo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableDescription(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetDescription(*s)
	}
	return auo
}

// SetRole sets the "role" field.
func (auo *AccountUpdateOne) SetRole(r role.Role) *AccountUpdateOne {
	auo.mutation.SetRole(r)
	return auo
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableRole(r *role.Role) *AccountUpdateOne {
	if r != nil {
		auo.SetRole(*r)
	}
	return auo
}

// AddMembershipIDs adds the "memberships" edge to the Membership entity by IDs.
func (auo *AccountUpdateOne) AddMembershipIDs(ids ...uuid.UUID) *AccountUpdateOne {
	auo.mutation.AddMembershipIDs(ids...)
	return auo
}

// AddMemberships adds the "memberships" edges to the Membership entity.
func (auo *AccountUpdateOne) AddMemberships(m ...*Membership) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return auo.AddMembershipIDs(ids...)
}

// AddInvitationIDs adds the "invitations" edge to the Invitation entity by IDs.
func (auo *AccountUpdateOne) AddInvitationIDs(ids ...uuid.UUID) *AccountUpdateOne {
	auo.mutation.AddInvitationIDs(ids...)
	return auo
}

// AddInvitations adds the "invitations" edges to the Invitation entity.
func (auo *AccountUpdateOne) AddInvitations(i ...*Invitation) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return auo.AddInvitationIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (auo *AccountUpdateOne) Mutation() *AccountMutation {
	return auo.mutation
}

// ClearMemberships clears all "memberships" edges to the Membership entity.
func (auo *AccountUpdateOne) ClearMemberships() *AccountUpdateOne {
	auo.mutation.ClearMemberships()
	return auo
}

// RemoveMembershipIDs removes the "memberships" edge to Membership entities by IDs.
func (auo *AccountUpdateOne) RemoveMembershipIDs(ids ...uuid.UUID) *AccountUpdateOne {
	auo.mutation.RemoveMembershipIDs(ids...)
	return auo
}

// RemoveMemberships removes "memberships" edges to Membership entities.
func (auo *AccountUpdateOne) RemoveMemberships(m ...*Membership) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return auo.RemoveMembershipIDs(ids...)
}

// ClearInvitations clears all "invitations" edges to the Invitation entity.
func (auo *AccountUpdateOne) ClearInvitations() *AccountUpdateOne {
	auo.mutation.ClearInvitations()
	return auo
}

// RemoveInvitationIDs removes the "invitations" edge to Invitation entities by IDs.
func (auo *AccountUpdateOne) RemoveInvitationIDs(ids ...uuid.UUID) *AccountUpdateOne {
	auo.mutation.RemoveInvitationIDs(ids...)
	return auo
}

// RemoveInvitations removes "invitations" edges to Invitation entities.
func (auo *AccountUpdateOne) RemoveInvitations(i ...*Invitation) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return auo.RemoveInvitationIDs(ids...)
}

// Where appends a list predicates to the AccountUpdate builder.
func (auo *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Account entity.
func (auo *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AccountUpdateOne) check() error {
	if v, ok := auo.mutation.Alias(); ok {
		if err := account.AliasValidator(v); err != nil {
			return &ValidationError{Name: "alias", err: fmt.Errorf(`ent: validator failed for field "Account.alias": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Name(); ok {
		if err := account.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Account.name": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Description(); ok {
		if err := account.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Account.description": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Role(); ok {
		if err := account.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "Account.role": %w`, err)}
		}
	}
	if _, ok := auo.mutation.OwnerID(); auo.mutation.OwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Account.owner"`)
	}
	if _, ok := auo.mutation.SiloID(); auo.mutation.SiloCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Account.silo"`)
	}
	return nil
}

func (auo *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Alias(); ok {
		_spec.SetField(account.FieldAlias, field.TypeString, value)
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
	}
	if value, ok := auo.mutation.Description(); ok {
		_spec.SetField(account.FieldDescription, field.TypeString, value)
	}
	if value, ok := auo.mutation.Role(); ok {
		_spec.SetField(account.FieldRole, field.TypeEnum, value)
	}
	if auo.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MembershipsTable,
			Columns: []string{account.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !auo.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MembershipsTable,
			Columns: []string{account.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MembershipsTable,
			Columns: []string{account.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.InvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.InvitationsTable,
			Columns: []string{account.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedInvitationsIDs(); len(nodes) > 0 && !auo.mutation.InvitationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.InvitationsTable,
			Columns: []string{account.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.InvitationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.InvitationsTable,
			Columns: []string{account.InvitationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invitation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Account{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
