// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/lesomnus/entpb/example/ent/account"
	"github.com/lesomnus/entpb/example/ent/identity"
	"github.com/lesomnus/entpb/example/ent/membership"
	"github.com/lesomnus/entpb/example/ent/user"
	"github.com/lesomnus/entpb/example/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountMixin := schema.Account{}.Mixin()
	accountMixinFields0 := accountMixin[0].Fields()
	_ = accountMixinFields0
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescDateCreated is the schema descriptor for date_created field.
	accountDescDateCreated := accountMixinFields0[1].Descriptor()
	// account.DefaultDateCreated holds the default value on creation for the date_created field.
	account.DefaultDateCreated = accountDescDateCreated.Default.(func() time.Time)
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountMixinFields0[0].Descriptor()
	// account.DefaultID holds the default value on creation for the id field.
	account.DefaultID = accountDescID.Default.(func() uuid.UUID)
	identityMixin := schema.Identity{}.Mixin()
	identityMixinFields0 := identityMixin[0].Fields()
	_ = identityMixinFields0
	identityFields := schema.Identity{}.Fields()
	_ = identityFields
	// identityDescDateCreated is the schema descriptor for date_created field.
	identityDescDateCreated := identityMixinFields0[1].Descriptor()
	// identity.DefaultDateCreated holds the default value on creation for the date_created field.
	identity.DefaultDateCreated = identityDescDateCreated.Default.(func() time.Time)
	// identityDescName is the schema descriptor for name field.
	identityDescName := identityFields[0].Descriptor()
	// identity.DefaultName holds the default value on creation for the name field.
	identity.DefaultName = identityDescName.Default.(string)
	// identityDescID is the schema descriptor for id field.
	identityDescID := identityMixinFields0[0].Descriptor()
	// identity.DefaultID holds the default value on creation for the id field.
	identity.DefaultID = identityDescID.Default.(func() uuid.UUID)
	membershipMixin := schema.Membership{}.Mixin()
	membershipMixinFields0 := membershipMixin[0].Fields()
	_ = membershipMixinFields0
	membershipFields := schema.Membership{}.Fields()
	_ = membershipFields
	// membershipDescDateCreated is the schema descriptor for date_created field.
	membershipDescDateCreated := membershipMixinFields0[1].Descriptor()
	// membership.DefaultDateCreated holds the default value on creation for the date_created field.
	membership.DefaultDateCreated = membershipDescDateCreated.Default.(func() time.Time)
	// membershipDescID is the schema descriptor for id field.
	membershipDescID := membershipMixinFields0[0].Descriptor()
	// membership.DefaultID holds the default value on creation for the id field.
	membership.DefaultID = membershipDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescDateCreated is the schema descriptor for date_created field.
	userDescDateCreated := userMixinFields0[1].Descriptor()
	// user.DefaultDateCreated holds the default value on creation for the date_created field.
	user.DefaultDateCreated = userDescDateCreated.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
