// Code generated by "protoc-gen-entpb". DO NOT EDIT

package pb

import (
	uuid "github.com/google/uuid"
)

func AccountById(k uuid.UUID) *GetAccountRequest {
	return &GetAccountRequest{Key: &GetAccountRequest_Id{Id: k[:]}}
}
func AccountByIdV(k []byte) *GetAccountRequest {
	return &GetAccountRequest{Key: &GetAccountRequest_Id{Id: k}}
}
func AccountByAlias(k string) *GetAccountRequest {
	return &GetAccountRequest{Key: &GetAccountRequest_Alias{Alias: k}}
}
func UserById(k uuid.UUID) *GetActorRequest {
	return &GetActorRequest{Id: k[:]}
}
func UserByIdV(k []byte) *GetActorRequest {
	return &GetActorRequest{Id: k}
}
func IdentityById(k uuid.UUID) *GetIdentityRequest {
	return &GetIdentityRequest{Id: k[:]}
}
func IdentityByIdV(k []byte) *GetIdentityRequest {
	return &GetIdentityRequest{Id: k}
}
func MembershipById(k uuid.UUID) *GetMembershipRequest {
	return &GetMembershipRequest{Id: k[:]}
}
func MembershipByIdV(k []byte) *GetMembershipRequest {
	return &GetMembershipRequest{Id: k}
}
