// Code generated by "protoc-gen-entpb". DO NOT EDIT

package bare

import (
	context "context"
	ent "github.com/lesomnus/entpb/example/ent"
	pb "github.com/lesomnus/entpb/example/pb"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type AccountServiceServer struct {
	db *ent.Client
	pb.UnimplementedAccountServiceServer
}

func (s *AccountServiceServer) Lock(context.Context, *pb.Account) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method not implemented")
}
