// Code generated by "protoc-gen-entpb". DO NOT EDIT

package bare

import (
	ent "github.com/lesomnus/entpb/example/ent"
	pb "github.com/lesomnus/entpb/example/pb"
)

type MembershipServiceServer struct {
	db *ent.Client
	pb.UnimplementedMembershipServiceServer
}
