// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// Identity is the predicate function for identity builders.
type Identity func(*sql.Selector)

// Membership is the predicate function for membership builders.
type Membership func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
